[book]
authors = ["侯建鹏"]
language = "zh"
multilingual = false
src = "."
title = "差分隐私算法基础"

[output.html]
mathjax-support = true
mathjax-config = "tex-mml-chtml"
git-repository-url = "https://github.com/HouJP/the-algorithmic-foundations-of-differential-privacy"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/HouJP/the-algorithmic-foundations-of-differential-privacy/edit/main/{path}"
